CREATE TABLE NAGT_NFE_STATUS_UFS (
  TIPO            VARCHAR2(10),
  ID              NUMBER,
  SIGLA           VARCHAR2(2),
  NOME_ESTADO     VARCHAR2(100),
  TEMPO_RESPOSTA  NUMBER,
  SVC             VARCHAR2(10),
  NORMAL          NUMBER(1),
  ATUALIZADO_EM   DATE DEFAULT SYSDATE
)
TABLESPACE USERS;
